-This is test code to preview the camera streaming from the ESP-32 CAM
-This code is taken from the Arduino library
-This is a reference for the final code used to run the DIY-Polaroid once the physical printer arrives 
